// <auto-generated />
using System;
using FluxoCaixa.Consolidado.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FluxoCaixa.Consolidado.Infrastructure.Migrations
{
    [DbContext(typeof(ConsolidadoDbContext))]
    [Migration("20260301030802_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FluxoCaixa.Consolidado.Domain.Entities.ProcessedEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ProcessedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ProcessedEvents", (string)null);
                });

            modelBuilder.Entity("FluxoCaixa.Consolidado.Domain.Entities.SaldoDiario", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalCredito")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalDebito")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("UserId", "Data");

                    b.HasIndex("UserId", "Data");

                    b.ToTable("SaldosDiarios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
